# Compilador
CC = gcc

# Arquivo de saída
OUT = app

# Diretórios
SRC_DIR = src
INC_DIR = include

# Arquivos-fonte
SRC = $(SRC_DIR)/main.c $(SRC_DIR)/api.c

# Flags de compilação
CFLAGS = -Wall -Wextra -g3 -I$(INC_DIR) -I/opt/homebrew/Cellar/cjson/1.7.18/include/cjson $(shell pkg-config --cflags libcurl)

# Flags de linkagem
LDFLAGS = -L/opt/homebrew/Cellar/cjson/1.7.18/lib -lcjson $(shell pkg-config --libs libcurl)

# Regra padrão
all: $(OUT)

$(OUT): $(SRC)
	$(CC) $(SRC) -o $(OUT) $(CFLAGS) $(LDFLAGS)

run: all
	./$(OUT)

clean:
	rm -f $(OUT) $(SRC_DIR)/*.o
